### ISSUE TITLE
[8.0] partner_relations - Error when deleting a res.partner

### ISSUE THREAD

**Issue by rafaelbn** [OCA/partner-contact#154]
Tested in OCA's runbot
https://runbot.odoo-community.org/runbot/repo/github-com-oca-partner-contact-134
- Create a partner
- Don't select "is a company"
- Filled "firstname" and "lastname"
- Save partner
- Delete the partner we have created
- You get this error:

> AccessError
> No value found for res.partner(75,).birthdate_date

I have tested in Odoo's runbot and you can delete any res.partner if it hasn't any other relation with other objects.

Maybe this bug it not from this module partner_contact_birthdate

@pedrobaeza I think that any module in this project must at least pass test of creating, modifying and deleting a res.partner, if not shouldn't be merged.

cc @sysadminmatmoz @Yajo

**Comment by pedrobaeza** [comment]
Tests are not mandatory for now in OCA to not discourage the contributions, and the review process usually detect these things.

I also think that this module is not the guilty, but something is happening.

**Comment by yajo** [comment]
Is `base_contact` installed? If so, try going to modules list, searching for `base_contact` and pressing _Update_.

**Comment by rafaelbn** [comment]
@Yajo base_contact is installed. After update still error.

I have uninstall lots of modules. Test & Try...

After uninstalling partner_firstname the problems disapears...

So ther is a bug in partner_firstname module https://github.com/OCA/partner-contact/pull/139

**Comment by eLBati** [comment]
@rafaelbn just tested on
http://3112595-8-0-359f6c.runbot1.odoo-community.org/
using the **base** database, installed `partner_firstname`, `partner_contact_birthdate` and `base_contact`: the error does not happen.

Please try to reproduce it on a new database, pointing out the modules to install. Traceback would be useful too.

Thanks

**Comment by yajo** [comment]
As a rule of thumb, I always press _Update_ in the `base` module after pulling new changes to any modules (core or OCA, any). That makes Odoo perform any updates needed and usually makes everything work smoothly. You could try that.

This bug seems to me more related to https://github.com/OCA/partner-contact/pull/120 than to #139. You can sniff all the code in `partner_firstname` and will find nothing related to birthdate.

And also you should try what @eLBati says.

**Comment by rafaelbn** [comment]
Please @Yajo add a test for deleting res.partner to partner_firstname, this could help now and in the future. Eventhogh I'm going now to test runbot again.

@eLBati howto traceback?

**Comment by rafaelbn** [comment]
@Yajo @eLBati 
- Log in in runbot OCA - partner-contact in a clean data base
  ^ Install crm module --> DELETION OK
- Install **partner_firstname** --> DELETION OK
- Install partner_contact_birthdate --> DELETION OK
- Install **partner_relations** --> FAILS DELETION. So here comes the problem. https://github.com/OCA/partner-contact/tree/8.0/partner_relations

The error I get is:

> AccessError
> No value found for res.partner(51,).street_name 
- Log in in runbot OCA - partner-contact in a clean data base
  ^ Install crm module --> DELETION OK
- Install **partner_relations** --> DELETION OK
- Install partner_contact_birthdate --> DELETION OK
- Install **partner_firstname** --> FAILS DELETION. So here comes the problem.

The error I get is:

> AccessError
> No value found for res.partner(17,).lastname 

Something between partners_firstname and partner_relations it's happening. Because why with all modules installed the error get fixed when uninstalling partner_firstname?

Please let me know, thanks.

cc @pedrobaeza @antespi @JavierIniesta

**Comment by rafaelbn** [comment]
```
openerp.http:540 _handle_exception
Exception during JSON request handling.
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/partner_contact_in_several_companies/models.py", line 127, in unlink
    return super(res_partner, self).unlink(cr, user, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/base/res/res_partner.py", line 537, in unlink
    return super(res_partner, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/mail/mail_thread.py", line 455, in unlink
    res = super(mail_thread, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 3663, in unlink
    recs.recompute()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5690, in recompute
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5690, in <dictcomp>
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5574, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5934, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', 'No value found for res.partner(75,).street_name')
```

```
openerp.http:540 _handle_exception
Exception during JSON request handling.
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/partner_contact_in_several_companies/models.py", line 127, in unlink
    return super(res_partner, self).unlink(cr, user, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/base/res/res_partner.py", line 537, in unlink
    return super(res_partner, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/mail/mail_thread.py", line 455, in unlink
    res = super(mail_thread, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 3663, in unlink
    recs.recompute()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5690, in recompute
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5690, in <dictcomp>
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5574, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5934, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', 'No value found for res.partner(75,).birthdate_date')
```

```
openerp.http:540 _handle_exception
Exception during JSON request handling.
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/base/res/res_partner.py", line 537, in unlink
    return super(res_partner, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/mail/mail_thread.py", line 455, in unlink
    res = super(mail_thread, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 3630, in unlink
    pool_model_data.unlink(cr, SUPERUSER_ID, reference_ids)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/addons/base/ir/ir_model.py", line 1018, in unlink
    return super(ir_model_data,self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 3663, in unlink
    recs.recompute()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5690, in recompute
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5690, in <dictcomp>
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5574, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/models.py", line 5934, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112595-8-0-359f6c/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', 'No value found for res.partner(17,).lastname')
```

**Comment by rafaelbn** [comment]
Please @antespi could you review this issue? Thanks

**Comment by rafaelbn** [comment]
@eLBati did you chack this? https://github.com/OCA/partner-contact/issues/154#issuecomment-131199584 Thanks

**Comment by eLBati** [comment]
I reproduced it installing `partner_contact_birthdate` and `partner_relations`.

Maybe modules authors can give some hint? ping @Yajo @hbrunn

**Comment by hbrunn** [comment]
put some breakpoints in the triggers involved, I assume some trigger tries to read the deleted patner afterwards

**Comment by rafaelbn** [comment]
@hbrunn @eLBati @pedrobaeza @antespi @Yajo question: if anyone add the test of deleting a partner in all modules in repo partner-contact then we will see when it happends. And by the way is a nice test.

**Comment by yajo** [comment]
The point is that `partner_firstname` and `partner_contact_birthdate` work flawlessly unless `partner_relations` is installed. It fails when there's a computed field trying to set a value in the model. This is expected behavior, that raises a `MissingError`, which gets skipped by the ORM. But when `partner_relations` is installed, computed fields raise `AccessError`, which bubbles to the user and prevents deletion.

Let me guess that any module adding a computed field to `res.partner` will fail.

I'm _fixing_ `partner_firstname` and `partner_contact_birthdate`, but I'm pretty sure the real bug is in `partner_relations`.

Does anybody know what is `partner_relations` doing? It's a very low-level module and I think it does something wrong, but after debugging for awhile I cannot find it.

**Comment by hbrunn** [comment]
@Yajo don't, the bug is fixed in #171

**Comment by yajo** [comment]
Testing #171 with #170 I discovered accidentally that partner_event is affected too:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 537, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 574, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 310, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 307, in checked_call
return self.endpoint(*a, **kw)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 803, in __call__
return self.method(*args, **kw)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 403, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 944, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_partner.py", line 537, in unlink
return super(res_partner, self).unlink(cr, uid, ids, context=context)
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/addons/mail/mail_thread.py", line 455, in unlink
res = super(mail_thread, self).unlink(cr, uid, ids, context=context)
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3630, in unlink
pool_model_data.unlink(cr, SUPERUSER_ID, reference_ids)
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 1018, in unlink
return super(ir_model_data,self).unlink(cr, uid, ids, context=context)
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3663, in unlink
recs.recompute()
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 239, in wrapper
return new_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5690, in recompute
name: rec[name] for name in names
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5690, in <dictcomp>
name: rec[name] for name in names
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5574, in __getitem__
return self._fields[key].__get__(self, type(self))
File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 823, in __get__
return record._cache[self]
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5934, in __getitem__
return value.get() if isinstance(value, SpecialValue) else value
File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 55, in get
raise self.exception
AccessError: ('AccessError', 'No value found for res.partner(43,).registrations')
```

**Comment by hbrunn** [comment]
@Yajo set a breakpoint in https://github.com/OCA/OCB/blob/8.0/openerp/fields.py#L53 and inspect what's going on when the failed value is created. Afterwards, the backtrace doesn't help a lot

**Comment by yajo** [comment]
One funny thing: if you remove [this read()](https://github.com/OCA/partner-contact/blob/8.0/partner_relations/model/res_partner.py#L301) method, the bug is fixed in all other modules. The bug resides in that method. I tested manually and with the tests in #170.

But `partner_relation` has no tests, so no way to check if that breaks it (and it will, probably).

This module needs much love. Migrating to v8 api would benefit it a lot (or to a more readable v7, it's very low-level even for that). And a test suite is a must for it.

I hope I have helped you to triage it, but I'm not going to touch this module's source for now. I'll keep #170 until you wish to merge it, as it does not hurt.

**Comment by yajo** [comment]
This is not fixed. See https://github.com/OCA/partner-contact/pull/170#issuecomment-141930996.

**Comment by rafaelbn** [comment]
@pedrobaeza @hbrunn I reopen this issue again. As @Yajo says is not fixed.

**I have tested in this moment again** in OCA runbot (partner-contact) and we still cannot delete a res.partner.

Problem is in module partner_relations (users could help @bwrsandman @antespi @hbrunn )

http://3115439-8-0-0c0503.runbot2.odoo-community.org/web?db=3115439-8-0-0c0503-all#menu_id=107&action=103

```
2015-09-22 00:48:47     ERROR   server  openerp.http:540 _handle_exception

Exception during JSON request handling.
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/addons/partner_contact_in_several_companies/models.py", line 127, in unlink
    return super(res_partner, self).unlink(cr, user, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/addons/base/res/res_partner.py", line 537, in unlink
    return super(res_partner, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/addons/mail/mail_thread.py", line 455, in unlink
    res = super(mail_thread, self).unlink(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/models.py", line 3665, in unlink
    recs.recompute()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/models.py", line 5721, in recompute
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/models.py", line 5721, in <dictcomp>
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/models.py", line 5605, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/models.py", line 5965, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3115439-8-0-0c0503/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', 'No value found for res.partner(75,).street_name')
```

From https://github.com/OCA/partner-contact/pull/103

**Comment by eLBati** [comment]
Hello, see my fix proposal at https://github.com/OCA/partner-contact/pull/200

**Comment by rafaelbn** [comment]
Fixed here: https://github.com/OCA/partner-contact/pull/200

Please review, thanks
