### ISSUE TITLE
[8.0] partner_firstname and "create and edit" in M2O widget to res.partner

### ISSUE THREAD

**Issue by alexis-via** [OCA/partner-contact#78]
Here are the steps to reproduce the bug on odoo v8 with an up-to-date branch of OCA/partner-contact/8.0:

1) Create a new sale order
In the "Customer" field (M2O to res.partner), type "TOTOTEST1" (it should not be an existing partner) and then, in the down-drop list that appear, click on "Create and Edit..."
2) You get a pop-up that displays the form view of res.partner with:
Name = TOTOTEST1
Firstname = False
Lastname = False
3) in the partner pop-up, enter:
Lastname = de Lattre
Fistname =  Alexis
Street = 42 rue de la paix
and click on "Save" in the partner pop-up and save in the quotation form.
4) Go to the "Customers" menu. You will find a partner with:
Name = TOTOTEST1
Lastname = TOTOTEST1
Firstname = False
Street = 42 rue de la paix

Conclusion : when the module partner_firstname is installed, we have a bug with "Create and Edit..." in the M2O widget that point to res.partner.

**Comment by alexis-via** [comment]
Bug analysis:
When I log the calls to create and write:
On step 2 of the scenario, odoo doesn't call create nor write
On step 3 of the scenario, odoo will call BOTH create and write:
1) first it calls create() with vals = {'firstname': 'Alexis', 'lastname': 'de Lattre', 'street': '42 rue de la paix'}
2) then it calls write() with vals = {'lastname': 'TOTOTEST1', 'firstname': False}

**Comment by pankk** [comment]
Cannot reproduce as of 359f6cea0239415a0cc1af2d4e7d97d13c2290fb. This seems fixed with 24948156e329b5321507275200757a7b11c47cbf

**Comment by pedrobaeza** [comment]
Yeah, it seems so. I close this issue. If still present, feel free to reopen.

**Comment by alexis-via** [comment]
I just re-tested the scenario with an up-to-date odoo 8.0 and an up-to-date partner_firstname from the OCA branch for 8.0, and the bug is still present. The scenario to reproduce the bug hasn't changed. Please re-open.

**Comment by pankk** [comment]
My bad, the bug is still present.

**Comment by alexis-via** [comment]
@pedrobaeza It seems we need your "super-powers" to re-open this bug. I can't do that myself.

**Comment by pedrobaeza** [comment]
Done. I'll check it later to see if I can apport something.

**Comment by rafaelbn** [comment]
I have reproduced it. The bug exists.
Please @Yajo @antespi take a look in this issue.

**Comment by alexis-via** [comment]
This bug is still present with up-to-date code.

@pedrobaeza If you have some idea on how to dig into this bug, please let me know. I must say that I don't know where to start to try to fix this bug. So any idea would be welcomed.

**Comment by pedrobaeza** [comment]
Well, no special idea. I have overseen the code and cannot guess what can be the source of the problem. I can't work on this for now.

**Comment by yajo** [comment]
Please check https://github.com/OCA/partner-contact/issues/195.

**Comment by yajo** [comment]
> 2) You get a pop-up that displays the form view of res.partner with:
> Name = TOTOTEST1
> Firstname = False
> Lastname = False

Just making clear that this is fixed now in #195, but indeed steps 3 and 4 still fail.

**Comment by rafaelbn** [comment]
This issue is solved here: https://github.com/OCA/partner-contact/pull/198, you can close this issue :+1:

**Comment by alexis-via** [comment]
I confirm that the bug is now fixed ! Bravo !
